74 change orders
swsxm/speiseplan-projekt pull request #16
Opened 2024-08-29 11:52 UTC by MrPitz1

added date to orders
created changeOrders.jsx that displays orders like in cart
order quantity can be changed. past orders cant be displayed/changed
if quantity is set to 0, menu item will be removed from order. if order is empty, oreder will be removed

2024-08-29 12:19 UTC, swsxm requested changes
paar gedankenanstoesse

2024-08-29 12:19 UTC, swsxm commented on speiseplan_projekt/src/app/api/changeOrder/route.js
> +
keine validierung

2024-08-29 12:19 UTC, swsxm commented on speiseplan_projekt/src/app/api/getOrders/route.js
> +                _id: meal._id,  // Include _id from orderedMeals
die _id wird hier nicht benoetigt meiner meinung nach und ist legacy code

2024-08-29 12:19 UTC, swsxm commented on speiseplan_projekt/src/app/api/getOrders/route.js
> +
meiner meinung noch sollte das alles eine mongo abfrage sein die die orders mit den meals joined

2024-08-29 12:19 UTC, swsxm commented on speiseplan_projekt/src/app/api/getOrders/route.js
> +
dementsprechend wenn man das ueber die abfrage macht waere das ueberfluessig mMn

2024-08-29 12:19 UTC, swsxm commented on speiseplan_projekt/src/app/api/order/route.js
> +        orderDate.setUTCHours(0, 0, 0, 0);
warum brauchen wir hier das zusaetzliche date ding?

2024-08-29 12:19 UTC, swsxm commented on speiseplan_projekt/src/app/profile/changeOrder/page.tsx
> +  orderMealId: string; // Stores the _id of the orderedMeals
was ist der unterschied zu _id

2024-08-29 12:19 UTC, swsxm commented on speiseplan_projekt/src/app/api/getOrders/route.js
> +
keine validierung

2024-08-29 12:19 UTC, swsxm commented on speiseplan_projekt/src/app/api/changeOrder/route.js
> +        targetDate.setUTCHours(0, 0, 0, 0); // Set time to 00:00:00 for accurate date matching
das benutzt du auch relativ oft evtl lib/datetime function?

2024-08-31 18:45 UTC, JonasPfi requested changes
Ich stimme den Anmerkungen von Simon zu. Habe noch paar stellen Kommentiert wo usere coding guideline nicht eingehalten wurden. Die bitte noch anpassen. Du kannst auch zu jeder neuen Seite und zu jeder api route die du gemacht schon mal einen testfall anlegen, damit dieser im coverage report auftaucht und später nix vergessen wird. Die Test kann man auch später noch schreiben.

2024-08-31 18:45 UTC, JonasPfi commented on speiseplan_projekt/src/app/api/order/route.js
> +     * Order logic here
Den Kommentar könnte man noch deutlicher formulieren

2024-08-31 18:45 UTC, JonasPfi commented on speiseplan_projekt/src/app/profile/cart/page.tsx
> +   * Shopping cart logic
Auch hier nichtssagender Kommentar

2024-08-31 18:45 UTC, JonasPfi commented on speiseplan_projekt/src/app/profile/cart/page.tsx
> +            console.log('Item Preis:', item.price); // Print the price for each item
Englisch bitte

2024-08-31 18:45 UTC, JonasPfi commented on speiseplan_projekt/src/app/profile/cart/page.tsx
>            console.warn("Unerwartete Datenstruktur im Local Storage gefunden");
Englisch bitte

2024-08-31 18:45 UTC, JonasPfi commented on speiseplan_projekt/src/app/profile/changeOrder/page.tsx
> +    function checkIfPastDate(date: Date | null): boolean {
Keine Funktion ist kommentiert

2024-08-31 18:45 UTC, JonasPfi commented on speiseplan_projekt/src/app/profile/changeOrder/page.tsx
> +      console.error("Fehler beim Bestätigen der Änderungen:", error);
Der Log muss englisch sein

2024-08-31 18:45 UTC, JonasPfi commented on speiseplan_projekt/src/app/speiseplan/page.tsx
> +    console.log(item.price)
Log für debugging. Kann der weg?

2024-08-31 18:45 UTC, JonasPfi commented on speiseplan_projekt/src/components/Modal.tsx
>    const [itemAdded, setItemAdded] = useState(false); // Zustand, um zu überprüfen, ob das Element bereits hinzugefügt wurde
Deutsche Kommentare müssen entweder weg oder eng

2024-09-02 16:13 UTC, closed without merging