79 testing login
swsxm/speiseplan-projekt pull request #26
Opened 2024-09-09 16:53 UTC by JonasPfi

Hier die restlichen Test von der User Story. Dazu auch gleich bugfixes weil die test an einigen stellen gleich fehler in der implementierung gezeigt haben. Bitte nochmal testen und drüber schauen

2024-09-10 13:54 UTC, swsxm approved these changes
Coverage passt, Test schauen gut aus, alle requirements der user story erfuellt wuerde ich sagen (kommentare eher sperrlich und useless)

2024-09-10 14:18 UTC, swsxm requested changes
du hast im commit "Added tests for login api route" ( api/login/route.js) das schema fuer die die validierung geaendert mit Statuscode Aenderung -> das funktioniert jetzt nicht mehr mit dem Frontend + die rueckgabee Invalid password ist information disclosure

2024-09-11 11:48 UTC, JonasPfi commented
Ich habe das information disclosure raus gemacht. Da ist jetzt dennoch ein message element das leer ist. Mein Problem war das die Test bei diesen Fehlern wenn da nur der status drin ist alle den status 200 bekommen, was falsch ist. So wie es jetzt ist sollte das frontend gehen. Zumindest geht bei mir alles

2024-09-11 12:00 UTC, swsxm approved these changes

2024-09-11 12:00 UTC, swsxm commented on speiseplan_projekt/src/app/login/page.tsx
> +      }
Schoener waere es einfach von der Api die message zurueckgeben also das was im else steht, so ist das bisschen ugly wenn die api "" zurueckgibt, das einzige problem ist dass die api im catch block den server error zurueckgibt die sollte eigentlich dann nur 500 Server Error zurueckgeben, das ist bei vielen apis von uns aber so und ein anderes bier..

2024-09-11 12:07 UTC, merged