Refactor of Database Model + registration validation
swsxm/speiseplan-projekt pull request #3
Opened 2024-08-19 18:26 UTC by swsxm

This PR introduces significant changes to the database model. The week model has been removed, and its functionality has been integrated directly into the plan model. Additionally, lookups are now performed using Object_IDs, allowing for direct references. Initial validation for user registration has also been implemented and also some datetime functions replaced with a library.

Please check the changes, and also test if everything is still working as expected.

Coding guidelines are only applied to the validation because refactoring everything is a different story.

2024-08-20 18:50 UTC, JonasPfi requested changes
Ja es war nicht der sinn alle Kommentare auf eng zu übersetzen, aber bei deinem neuen Code den du schreibst bitte nochmal alles auf englisch machen und an manchen stellen wirklich viel zu viele Kommentare

2024-08-20 18:50 UTC, JonasPfi commented on speiseplan_projekt/src/lib/datetimeHelpers.js
> +
Kommentare fehlen. Kurz was ist der sinn auf englisch

2024-08-20 18:50 UTC, JonasPfi commented on speiseplan_projekt/src/app/api/fetchType/route.js
> -        return NextResponse.json(meals, { status: 201 });
Neue Kommentare auf englisch & zu viele Kommentare

2024-08-20 18:50 UTC, JonasPfi commented on speiseplan_projekt/src/app/admin/create-menu/page.tsx
Ich denke Kommentare hier noch deutsch, weil das in einer anderen Story gemacht wird. Hier nur basic einrücken

2024-08-20 18:50 UTC, JonasPfi commented on speiseplan_projekt/src/app/api/getMenuCreate/route.js
Zu viele Kommentare und net englisch

2024-08-20 18:50 UTC, JonasPfi commented on speiseplan_projekt/src/app/api/nextWeek/route.js
Zu viele Kommentare und net englisch

2024-08-20 18:50 UTC, JonasPfi commented on speiseplan_projekt/src/app/api/register/route.js
Wunderschön

2024-08-20 18:50 UTC, JonasPfi commented on speiseplan_projekt/src/app/api/updateMenuItem/route.js
Kommentare net englisch

2024-08-20 18:50 UTC, JonasPfi commented on speiseplan_projekt/src/models/orders.js
> +            type: Schema.Types.ObjectId, // Referenziert das Meal-Schema
Kommentar überflüssig? und wenn dann englisch

2024-08-20 21:11 UTC, swsxm commented on speiseplan_projekt/src/app/api/register/route.js
Legacy code (nicht von mir danke).

2024-08-21 19:06 UTC, JonasPfi approved these changes
Geil

2024-08-21 19:07 UTC, merged